name: 'build-test'
on:
  push:

jobs:
  test:
    name: run test as jest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: install eslint
        run: |
          npm install -g eslint
      - name: install jest
        run: |
          npm install -g jest
      - name: install
        run: |
          npm install
      - name: lint
        run: |
          npm run lint
      - name: test
        run: |
          npm run test
      - name: git setting
        run: |
          git config --local user.email "t.nagashima.cog@gmail.com"
          git config --local user.name "2or3"
      - name: push
        run: |
          set +e
          git add .
          git commit -m"[Github action] formatted by eslint and jest report" -a
          git pull
          git push origin main
  deploy:
    name: deploy as cdk
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: install typescript
        run: |
          npm install -g typescript
      - name: install
        run: |
          npm install
      - name: build
        run: |
          npm run build
      - name: cdk bootstrap
        run: |
          cdk bootstrap aws://${{ secrets.AWS_ACCOUNT }}/${{ secrets.AWS_DEFAULT_REGION }}
      - name: deploy
        run: |
          npm run deploy
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}